---
title: "conceitos_mineração de textos"
author: "Joachim"
date: "03/07/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("knitr")

library(tidyverse)
```

```{r importação de dados}
transporte1<- read.csv("sc_direct_transporte1.csv", colClasses = "character")
transporte2<- read.csv("sc_direct_transporte2.csv",colClasses = "character") 
transporte3<- read.csv("sc_direct_transporte3.csv",colClasses = "character") 

transporte_tudo <- list(transporte1, transporte2, transporte3)

transporte_tudo<- transporte_tudo %>% 
  map(select, c(Author,Title, Custom1)) %>% 
  map(rename, "Abstract" = Custom1)
```

```{r nuvem de palavras}
library("wordcloud")
library("tm")
library("tidytext")
library("textstem")
library("lexiconPT")


tokens_transporte <- transporte_tudo %>%
 map(unnest_tokens, palavra, Abstract, strip_numeric=TRUE) 


stopwords <- get_stopwords(language="en") %>%
  rename(palavra=word)

tokens_transporte<- tokens_transporte %>%
  map(anti_join, stopwords, by ="palavra")

tokens_transporte %>%  
  map(pull, palavra) %>% 
  map(wordcloud)


```

```{r transporte_frequencia de conceitos }


freq_conceitos <- tokens_transporte %>%  
  map(filter, palavra %in% c("bribery", "lobbying", "fraud", "influence", "abuse", "capture", "nepotism", "extortion", "Grand" , "Petty", "corruption") ) %>% 
  map(count, palavra)


```


```{r}

```

